CREATE DATABASE IF NOT EXISTS OFICINA_MECANICA_SAEP_DB;
USE OFICINA_MECANICA_SAEP_DB; 

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_ID INT AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR (100) NOT NULL,
    USU_EMAIL VARCHAR (100) NOT NULL,
    USU_SENHA VARCHAR (100) NOT NULL
);

CREATE TABLE IF NOT EXISTS CLIENTE (
	CLI_ID INT AUTO_INCREMENT PRIMARY KEY,
    CLI_NOME VARCHAR (100) NOT NULL,
    CLI_DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS VEICULO (
	VEI_ID INT AUTO_INCREMENT PRIMARY KEY,
    VEI_NOME VARCHAR (100) NOT NULL,
    VEI_DATA_LANCAMENTO DATE NOT NULL,
    FK_CLI_ID INT NOT NULL,
    FOREIGN KEY (FK_CLI_ID) REFERENCES CLIENTE(CLI_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS AGENDAMENTO (
	AGE_ID INT AUTO_INCREMENT PRIMARY KEY,
    AGE_DATA_HORA DATETIME NOT NULL,
    AGE_MOTIVO VARCHAR (100) NOT NULL,
    AGE_STATUS VARCHAR (30) NOT NULL,
    FK_VEI_ID INT NOT NULL,
    FK_CLI_ID INT NOT NULL,
    FOREIGN KEY (FK_VEI_ID) REFERENCES VEICULO(VEI_ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CLI_ID) REFERENCES CLIENTE(CLI_ID) ON DELETE CASCADE
);

INSERT INTO USUARIO( USU_NOME, USU_EMAIL, USU_SENHA)
VALUES("Admin", "admin@admin.com", "admin123"),
	("Bruno", "bruno@email.com", "123456"),
    ("Luiz", "luiz@email.com", "123456");

INSERT INTO CLIENTE( CLI_NOME, CLI_DATA_NASCIMENTO)
VALUES ("Bruno","2008-08-28"), -- RES_ID - 1
		("Luiz","1800-01-10"), -- RES_ID - 2
        ("Leonardo","1998-10-10"); -- RES_ID - 3
        
INSERT INTO VEICULO( VEI_NOME, VEI_DATA_LANCAMENTO, FK_CLI_ID)
VALUES ("RONDA", "2024-04-05", 2), -- PAC_ID - 1
		("UNO", "2025-07-21", 1), -- PAC_ID - 2
        ("CELTA", "2020-10-01", 3); -- PAC_ID - 3

INSERT INTO AGENDAMENTO( AGE_DATA_HORA, AGE_MOTIVO, AGE_STATUS, FK_VEI_ID, FK_CLI_ID)
VALUES ("2026-09-29 08:00:00","VAZAMENTO","Agendada","1","2"),
		("2026-09-29 08:30:00","PNEU FURADO","Agendada","2","1"),
        ("2026-09-29 09:00:00","LANTERNA QUEBRADA","Agendada","3","3");
        


